//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BergerStepWiseData
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BergerStepWiseData()
        {
            this.BergerXPPaymentTransactions = new HashSet<BergerXPPaymentTransaction>();
        }
    
        public int BergerStepWiseDataId { get; set; }
        public int BusinessQueryID { get; set; }
        public Nullable<bool> IsStep2Completed { get; set; }
        public Nullable<int> BergerLookingForPaintId { get; set; }
        public Nullable<bool> IsStep3Completed { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BergerPaintTypeId { get; set; }
        public Nullable<double> CarpetArea { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public Nullable<int> NoOfFloors { get; set; }
        public Nullable<int> InteriorWaterproofingForId { get; set; }
        public Nullable<int> ExteriorWaterproofingForId { get; set; }
        public Nullable<int> BergerWaterproofingTypeId { get; set; }
        public Nullable<int> BergerLocalityId { get; set; }
        public string OtherLocality { get; set; }
        public Nullable<bool> IsStep4Completed { get; set; }
        public Nullable<bool> IsSelectOnlinePayment { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> IsSelectOnSiteVisit { get; set; }
        public Nullable<bool> IsOTPValidated { get; set; }
        public Nullable<int> BergerLPCityId { get; set; }
        public string BergerLocalityName { get; set; }
        public string BergerLocalityGUID { get; set; }
    
        public virtual tbl_BusinessQuery tbl_BusinessQuery { get; set; }
        public virtual BergerLookingForPaint BergerLookingForPaint { get; set; }
        public virtual InteriorWaterproofingFor InteriorWaterproofingFor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BergerXPPaymentTransaction> BergerXPPaymentTransactions { get; set; }
        public virtual BergerPaintType BergerPaintType { get; set; }
        public virtual BergerPaintType BergerPaintType1 { get; set; }
        public virtual ExteriorWaterproofingFor ExteriorWaterproofingFor { get; set; }
    }
}
