//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BergerXPPaymentTransaction
    {
        public int BergerXPPaymentTransactionId { get; set; }
        public int BergerStepWiseDataId { get; set; }
        public string TransactionReferenceId { get; set; }
        public double Amount { get; set; }
        public string PaymentId { get; set; }
        public string OrderId { get; set; }
        public string PaymentStatus { get; set; }
        public Nullable<bool> IsPaymentSucceed { get; set; }
        public string PaymentMethod { get; set; }
        public string CardId { get; set; }
        public string Bank { get; set; }
        public string Wallet { get; set; }
        public string VPA { get; set; }
        public string ErrorCode { get; set; }
        public string ErrorDescription { get; set; }
        public string ErrorSource { get; set; }
        public string ErrorStep { get; set; }
        public string ErrorReason { get; set; }
        public Nullable<bool> IsSentEmailToUser { get; set; }
        public Nullable<bool> IsSentEmailToAdmin { get; set; }
        public Nullable<int> BergerXPPaymentCallBackConfigId { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual BergerStepWiseData BergerStepWiseData { get; set; }
    }
}
