//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class BergerGlobalChatbotLead
    {
        public int BergerGlobalChatbotLeadId { get; set; }
        public int BusinessQueryID { get; set; }
        public string Rating { get; set; }
        public string LeadOpprtunity { get; set; }
        public string EnquiryQualifiedSource { get; set; }
        public string EnquiryQualifiedStatus { get; set; }
        public string EnquiryDescription { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
