//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BergerPhase3Entities : DbContext
    {
        public BergerPhase3Entities()
            : base("name=BergerPhase3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BergerGlobalChatbotLead> BergerGlobalChatbotLeads { get; set; }
        public virtual DbSet<BergerStepWiseData> BergerStepWiseDatas { get; set; }
        public virtual DbSet<CRMCampaignLocation> CRMCampaignLocations { get; set; }
        public virtual DbSet<CRMFacebookECFLead> CRMFacebookECFLeads { get; set; }
        public virtual DbSet<CRMFacebookLead> CRMFacebookLeads { get; set; }
        public virtual DbSet<CRMFacebookSBELead> CRMFacebookSBELeads { get; set; }
        public virtual DbSet<CRMGoogleLead> CRMGoogleLeads { get; set; }
        public virtual DbSet<CRMInstagramLead> CRMInstagramLeads { get; set; }
        public virtual DbSet<CRMLeadSubStatu> CRMLeadSubStatus { get; set; }
        public virtual DbSet<CRMLeadSyncStatu> CRMLeadSyncStatus { get; set; }
        public virtual DbSet<CRMLinkedinLead> CRMLinkedinLeads { get; set; }
        public virtual DbSet<crmVendorLead> crmVendorLeads { get; set; }
        public virtual DbSet<FacebookFormDetail> FacebookFormDetails { get; set; }
        public virtual DbSet<tbl_AskConsultant> tbl_AskConsultant { get; set; }
        public virtual DbSet<tbl_BusinessQuery> tbl_BusinessQuery { get; set; }
        public virtual DbSet<tbl_ConstructionChemicalEnquiry> tbl_ConstructionChemicalEnquiry { get; set; }
        public virtual DbSet<tbl_HomePaintingEnquiry> tbl_HomePaintingEnquiry { get; set; }
        public virtual DbSet<tbl_IndustrialUsers_Enquiry> tbl_IndustrialUsers_Enquiry { get; set; }
        public virtual DbSet<tbl_ProductEnquiry> tbl_ProductEnquiry { get; set; }
        public virtual DbSet<tbl_UnderCoatEnquiry> tbl_UnderCoatEnquiry { get; set; }
        public virtual DbSet<CRMSource> CRMSources { get; set; }
        public virtual DbSet<BergerLookingForPaint> BergerLookingForPaints { get; set; }
        public virtual DbSet<BergerXPPaymentTransaction> BergerXPPaymentTransactions { get; set; }
        public virtual DbSet<InteriorWaterproofingFor> InteriorWaterproofingFors { get; set; }
        public virtual DbSet<BergerPaintType> BergerPaintTypes { get; set; }
        public virtual DbSet<ExteriorWaterproofingFor> ExteriorWaterproofingFors { get; set; }
        public virtual DbSet<ChatbotLeadsOtherSource> ChatbotLeadsOtherSources { get; set; }
        public virtual DbSet<tbl_BusinessDealer> tbl_BusinessDealer { get; set; }
        public virtual DbSet<tbl_BusinessDealerAdditionalData> tbl_BusinessDealerAdditionalData { get; set; }
        public virtual DbSet<tbl_Dealer> tbl_Dealer { get; set; }
        public virtual DbSet<tbl_SocialPainting> tbl_SocialPainting { get; set; }
        public virtual DbSet<VideoCategory> VideoCategories { get; set; }
        public virtual DbSet<WarrantyCertificateFor> WarrantyCertificateFors { get; set; }
        public virtual DbSet<WarrantyCertificateOtherDetail> WarrantyCertificateOtherDetails { get; set; }
        public virtual DbSet<WarrantyCertificateProduct> WarrantyCertificateProducts { get; set; }
        public virtual DbSet<WarrantyCertificateProductDetail> WarrantyCertificateProductDetails { get; set; }
        public virtual DbSet<WarrantyCertificateUser> WarrantyCertificateUsers { get; set; }
        public virtual DbSet<WarrantyHomeshieldApplication> WarrantyHomeshieldApplications { get; set; }
        public virtual DbSet<WarrantyHomeshieldOtherDetail> WarrantyHomeshieldOtherDetails { get; set; }
        public virtual DbSet<WarrantyHomeshieldProductApplication> WarrantyHomeshieldProductApplications { get; set; }
        public virtual DbSet<WarrantyHomeshieldUploadDocument> WarrantyHomeshieldUploadDocuments { get; set; }
        public virtual DbSet<WarrantyHomeshieldUser> WarrantyHomeshieldUsers { get; set; }
        public virtual DbSet<WarrantyPincode> WarrantyPincodes { get; set; }
        public virtual DbSet<WarrantyState> WarrantyStates { get; set; }
    }
}
