//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChatbotLeadsOtherSource
    {
        public int ChatbotLeadsOtherSourcesDataId { get; set; }
        public int BusinessQueryID { get; set; }
        public Nullable<bool> IsStep2Completed { get; set; }
        public Nullable<int> BergerLookingForPaintId { get; set; }
        public Nullable<bool> IsStep3Completed { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> BergerPaintTypeId { get; set; }
        public Nullable<double> CarpetArea { get; set; }
        public Nullable<int> NoOfRooms { get; set; }
        public Nullable<int> NoOfFloors { get; set; }
        public Nullable<int> InteriorWaterproofingForId { get; set; }
        public Nullable<int> ExteriorWaterproofingForId { get; set; }
        public Nullable<int> BergerWaterproofingTypeId { get; set; }
        public Nullable<int> BergerLocalityId { get; set; }
        public Nullable<bool> IsStep4Completed { get; set; }
        public Nullable<bool> IsSelectOnlinePayment { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<bool> IsSelectOnSiteVisit { get; set; }
        public Nullable<bool> IsOTPValidated { get; set; }
        public string OtherLocality { get; set; }
        public Nullable<int> BergerLPCityId { get; set; }
        public string BergerLocalityGUID { get; set; }
        public string BergerLocalityName { get; set; }
        public string Rating { get; set; }
        public string LeadOpprtunity { get; set; }
        public string EnquiryQualifiedSource { get; set; }
        public string EnquiryQualifiedStatus { get; set; }
        public string EnquiryDescription { get; set; }
        public string Address { get; set; }
    
        public virtual BergerLookingForPaint BergerLookingForPaint { get; set; }
        public virtual BergerPaintType BergerPaintType { get; set; }
        public virtual BergerPaintType BergerPaintType1 { get; set; }
        public virtual CRMFacebookLead CRMFacebookLead { get; set; }
        public virtual ExteriorWaterproofingFor ExteriorWaterproofingFor { get; set; }
        public virtual InteriorWaterproofingFor InteriorWaterproofingFor { get; set; }
    }
}
