//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMLeadSubStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRMLeadSubStatu()
        {
            this.CRMFacebookECFLeads = new HashSet<CRMFacebookECFLead>();
            this.CRMFacebookSBELeads = new HashSet<CRMFacebookSBELead>();
            this.CRMGoogleLeads = new HashSet<CRMGoogleLead>();
            this.CRMInstagramLeads = new HashSet<CRMInstagramLead>();
            this.CRMLinkedinLeads = new HashSet<CRMLinkedinLead>();
            this.crmVendorLeads = new HashSet<crmVendorLead>();
            this.tbl_AskConsultant = new HashSet<tbl_AskConsultant>();
            this.tbl_ConstructionChemicalEnquiry = new HashSet<tbl_ConstructionChemicalEnquiry>();
            this.tbl_HomePaintingEnquiry = new HashSet<tbl_HomePaintingEnquiry>();
            this.tbl_IndustrialUsers_Enquiry = new HashSet<tbl_IndustrialUsers_Enquiry>();
            this.tbl_ProductEnquiry = new HashSet<tbl_ProductEnquiry>();
            this.tbl_UnderCoatEnquiry = new HashSet<tbl_UnderCoatEnquiry>();
            this.CRMFacebookLeads = new HashSet<CRMFacebookLead>();
            this.tbl_BusinessQuery = new HashSet<tbl_BusinessQuery>();
            this.WarrantyHomeshieldApplications = new HashSet<WarrantyHomeshieldApplication>();
        }
    
        public int CRMLeadSubStatusId { get; set; }
        public int CRMLeadMainStatusId { get; set; }
        public string CRMLeadSubStatus { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMFacebookECFLead> CRMFacebookECFLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMFacebookSBELead> CRMFacebookSBELeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMGoogleLead> CRMGoogleLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMInstagramLead> CRMInstagramLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMLinkedinLead> CRMLinkedinLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmVendorLead> crmVendorLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AskConsultant> tbl_AskConsultant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ConstructionChemicalEnquiry> tbl_ConstructionChemicalEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HomePaintingEnquiry> tbl_HomePaintingEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_IndustrialUsers_Enquiry> tbl_IndustrialUsers_Enquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProductEnquiry> tbl_ProductEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UnderCoatEnquiry> tbl_UnderCoatEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMFacebookLead> CRMFacebookLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessQuery> tbl_BusinessQuery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarrantyHomeshieldApplication> WarrantyHomeshieldApplications { get; set; }
    }
}
