//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMLeadSyncStatu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRMLeadSyncStatu()
        {
            this.CRMFacebookECFLeads = new HashSet<CRMFacebookECFLead>();
            this.CRMFacebookSBELeads = new HashSet<CRMFacebookSBELead>();
            this.CRMGoogleLeads = new HashSet<CRMGoogleLead>();
            this.CRMInstagramLeads = new HashSet<CRMInstagramLead>();
            this.CRMLinkedinLeads = new HashSet<CRMLinkedinLead>();
            this.crmVendorLeads = new HashSet<crmVendorLead>();
            this.CRMFacebookLeads = new HashSet<CRMFacebookLead>();
        }
    
        public int CRMLeadSyncStatusId { get; set; }
        public string CRMLeadSyncStatus { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMFacebookECFLead> CRMFacebookECFLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMFacebookSBELead> CRMFacebookSBELeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMGoogleLead> CRMGoogleLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMInstagramLead> CRMInstagramLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMLinkedinLead> CRMLinkedinLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<crmVendorLead> crmVendorLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CRMFacebookLead> CRMFacebookLeads { get; set; }
    }
}
