//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRMSource
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CRMSource()
        {
            this.tbl_AskConsultant = new HashSet<tbl_AskConsultant>();
            this.tbl_ConstructionChemicalEnquiry = new HashSet<tbl_ConstructionChemicalEnquiry>();
            this.tbl_HomePaintingEnquiry = new HashSet<tbl_HomePaintingEnquiry>();
            this.tbl_IndustrialUsers_Enquiry = new HashSet<tbl_IndustrialUsers_Enquiry>();
            this.tbl_ProductEnquiry = new HashSet<tbl_ProductEnquiry>();
            this.tbl_UnderCoatEnquiry = new HashSet<tbl_UnderCoatEnquiry>();
            this.tbl_BusinessQuery = new HashSet<tbl_BusinessQuery>();
            this.tbl_BusinessDealer = new HashSet<tbl_BusinessDealer>();
            this.WarrantyHomeshieldApplications = new HashSet<WarrantyHomeshieldApplication>();
        }
    
        public int CRMSourceId { get; set; }
        public string Source { get; set; }
        public string CallInfo { get; set; }
        public string LeadSource { get; set; }
        public bool IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_AskConsultant> tbl_AskConsultant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ConstructionChemicalEnquiry> tbl_ConstructionChemicalEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_HomePaintingEnquiry> tbl_HomePaintingEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_IndustrialUsers_Enquiry> tbl_IndustrialUsers_Enquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_ProductEnquiry> tbl_ProductEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_UnderCoatEnquiry> tbl_UnderCoatEnquiry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessQuery> tbl_BusinessQuery { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessDealer> tbl_BusinessDealer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WarrantyHomeshieldApplication> WarrantyHomeshieldApplications { get; set; }
    }
}
