//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExteriorWaterproofingFor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExteriorWaterproofingFor()
        {
            this.BergerStepWiseDatas = new HashSet<BergerStepWiseData>();
            this.ChatbotLeadsOtherSources = new HashSet<ChatbotLeadsOtherSource>();
        }
    
        public int ExteriorWaterproofingForId { get; set; }
        public string ExteriorWaterproofingFor1 { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string DataBindName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BergerStepWiseData> BergerStepWiseDatas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatbotLeadsOtherSource> ChatbotLeadsOtherSources { get; set; }
    }
}
