//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BusinessDealerAdditionalData
    {
        public int tbl_BusinessDealerAdditionalDataID { get; set; }
        public Nullable<int> BusinessDealerID { get; set; }
        public string Call_Center_status { get; set; }
        public string Call_Center_last_Followup_Date { get; set; }
        public string Call_Center_next_Followup_Date { get; set; }
        public string Customer_Name { get; set; }
        public string separate_column_not_needed_since_there_in_enquiry { get; set; }
        public string Lead_ID { get; set; }
        public string Lead_Status { get; set; }
        public string Lead_Created_Date { get; set; }
        public string Cancellation_reason { get; set; }
        public string Cancellation_remarks { get; set; }
        public string Assigned_Depot { get; set; }
        public string Assigned_ASM { get; set; }
        public string Assigned_TSI { get; set; }
        public string Converted_Dealer_code { get; set; }
        public string Converted_Dealer_type { get; set; }
        public string Converted_sub_dealer_code { get; set; }
        public string Business_Line { get; set; }
        public string GST_YorN { get; set; }
        public string Gst_No { get; set; }
        public string Shop_Name { get; set; }
        public string Shop_Address_1 { get; set; }
        public string Shop_Address_2 { get; set; }
        public string Shop_City { get; set; }
        public string Shop_State { get; set; }
        public string Shop_Pin { get; set; }
        public string Current_sales_value_lakh { get; set; }
        public string Start_Dealing_Berger_product_Within { get; set; }
        public string Current_segment { get; set; }
        public string Current_brands { get; set; }
        public string Lead_Remarks { get; set; }
        public string Lead_Remarks_Date { get; set; }
        public string Fresh_Lead_Last_Followup_Status { get; set; }
        public string Fresh_Lead_Last_Followup_On { get; set; }
        public string Fresh_Lead_Next_Followup_On { get; set; }
        public string Home_Address_2 { get; set; }
        public string Home_City { get; set; }
        public string Home_State { get; set; }
        public string Home_Pin { get; set; }
        public string Customer_Mobile { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual tbl_BusinessDealer tbl_BusinessDealer { get; set; }
    }
}
