//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_SocialPainting
    {
        public int ID { get; set; }
        public string NameOfSociety { get; set; }
        public string Pincode { get; set; }
        public string Area { get; set; }
        public string City { get; set; }
        public int NumberOfFlats { get; set; }
        public string HelpOptions { get; set; }
        public string ContactPerson { get; set; }
        public string PresidentSecretaryCommiteeName { get; set; }
        public string ContactNumber { get; set; }
        public string ContactEmailId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsRecieveWhatsAppUpdate { get; set; }
        public bool isPincodeServicable { get; set; }
        public Nullable<bool> IsSendToChatbot { get; set; }
        public Nullable<int> UTM_Source { get; set; }
        public string UTM_Campaign { get; set; }
        public string UTM_Medium { get; set; }
    }
}
