//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_BusinessDealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_BusinessDealer()
        {
            this.tbl_BusinessDealerAdditionalData = new HashSet<tbl_BusinessDealerAdditionalData>();
        }
    
        public int BusinessDealerID { get; set; }
        public string Name { get; set; }
        public string Telephone { get; set; }
        public string Pincode { get; set; }
        public string City { get; set; }
        public string Email { get; set; }
        public string Language { get; set; }
        public string GSTNo { get; set; }
        public string Query { get; set; }
        public Nullable<bool> IsOwnAStore { get; set; }
        public Nullable<bool> AcceptedTerms { get; set; }
        public string Location { get; set; }
        public string Source { get; set; }
        public string Medium { get; set; }
        public string Campaign { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string Term { get; set; }
        public string Keyword { get; set; }
        public Nullable<int> CRMSourceId { get; set; }
        public string UrlReferrer { get; set; }
        public string Adgroup { get; set; }
        public Nullable<int> CRMCampaignLocationId { get; set; }
        public string Content { get; set; }
        public string GoogleClickLeadId { get; set; }
        public string LeadGenerationSource { get; set; }
        public Nullable<bool> IsSendtoAPI { get; set; }
        public Nullable<bool> IsChkWhatsAppAccept { get; set; }
        public string ShopName { get; set; }
    
        public virtual CRMSource CRMSource { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_BusinessDealerAdditionalData> tbl_BusinessDealerAdditionalData { get; set; }
    }
}
