//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyHomeshieldProductApplication
    {
        public int WarrantyHomeshieldProductApplicationId { get; set; }
        public int WarrantyHomeshieldApplicationId { get; set; }
        public int ProductId { get; set; }
        public bool IsUndercoat { get; set; }
        public string ProductName { get; set; }
        public double Quantity { get; set; }
        public string BatchNo { get; set; }
        public System.DateTime ManifacturingDate { get; set; }
        public double AreaCoatedWithProduct { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual WarrantyHomeshieldApplication WarrantyHomeshieldApplication { get; set; }
    }
}
