//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyCertificateProduct
    {
        public int WarrantyCertificateProductId { get; set; }
        public int ProductId { get; set; }
        public string Warranty { get; set; }
        public string WarrantyCardPhysicalPath { get; set; }
        public Nullable<int> ProductPriority { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> WarrantyTypeId { get; set; }
    }
}
