//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyCertificateOtherDetail
    {
        public int WarrantyCertificateOtherDetailId { get; set; }
        public int WarrantyCertificateUserId { get; set; }
        public string DealerName { get; set; }
        public string DealerContactNo { get; set; }
        public string ContratorName { get; set; }
        public string ContratorContactNo { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual WarrantyCertificateUser WarrantyCertificateUser { get; set; }
    }
}
