//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MTDSchedulerApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class WarrantyHomeshieldUploadDocument
    {
        public int DocumentId { get; set; }
        public int WarrantyHomeshieldUserId { get; set; }
        public string DocumentPath { get; set; }
        public System.DateTime CreatedDate { get; set; }
    
        public virtual WarrantyHomeshieldUser WarrantyHomeshieldUser { get; set; }
    }
}
